name: Convert images to WebP

on:
  push:
    branches: [ main ]          # change if your default branch is different
  workflow_dispatch:            # allow manual runs from the Actions tab

jobs:
  webp:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # needed to commit the generated .webp files

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install WebP tools
        run: |
          sudo apt-get update
          sudo apt-get install -y webp

      - name: Convert JPG/PNG to WebP
        id: convert
        env:
          QUALITY: '82'         # photo quality (75–90 recommended)
          MAX_WIDTH: '1200'     # resize width; 0 = keep original size
        shell: bash
        run: |
          set -e
          shopt -s globstar nullglob nocaseglob

          # Build candidate list (only under assets/gallery)
          files=()
          for f in assets/gallery/**/*.jpg assets/gallery/**/*.jpeg assets/gallery/**/*.png; do
            files+=("$f")
          done

          converted=0
          for f in "${files[@]}"; do
            out="${f%.*}.webp"
            # Skip if already converted
            if [[ -f "$out" ]]; then
              echo "Skip (exists): $out"
              continue
            fi
            # Choose lossless for graphics (png) and lossy for photos
            if [[ "$f" =~ \.png$ || "$f" =~ \.PNG$ ]]; then
              cwebp -lossless "$f" -o "$out"
            else
              if [[ "$MAX_WIDTH" == "0" ]]; then
                cwebp -q "$QUALITY" -m 6 "$f" -o "$out"
              else
                cwebp -q "$QUALITY" -m 6 -resize "$MAX_WIDTH" 0 "$f" -o "$out"
              fi
            fi
            echo "Converted: $f -> $out"
            converted=$((converted+1))
          done

          echo "converted=$converted" >> "$GITHUB_OUTPUT"

      - name: Commit WebP files
        if: steps.convert.outputs.converted != '0'
        uses: EndBug/add-and-commit@v9
        with:
          add: 'assets/gallery/**/*.webp'
          message: 'chore(webp): auto-convert gallery images [skip ci]'
          default_author: github_actions

      - name: No new images to convert
        if: steps.convert.outputs.converted == '0'
        run: echo "No JPG/PNG images needed conversion."
